language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.11"
  - "0.10"
after_script:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
  - codeclimate < ./coverage/lcov.info
addons:
  code_climate:
    repo_token: MWzLstbRsfOFj5jzNeNkXiJMJkZC1coeh